services:
  app:
    image: debian
    build: .
    volumes: 
      - ~/workspace:/workspace
    ports:
      - 3003:3003
      - 8004:8004
      - 5795:5795
      - 4003:4003
      - 443:443
      - 80:80
      - 8082:8082
    entrypoint: ["/bin/bash", "--login", "-c", "cd workspace/your-legacy-project && moov server --verify-ssl-cert=false"]
